#ifndef COMPILERPROJECT_STATES_H
#define COMPILERPROJECT_STATES_H

enum States {
    PARSER_DEFAULT = 0,
    PARSER_INIT_TOKEN,
    PARSER_BUILD_TOKEN,
    PARSER_BUILD_REAL,
    PARSER_RECORD_TOKEN,
    PARSER_COMMENT 
};

#endif //COMPILERPROJECT_STATES_H
